name: DIYAI
options:
  bundleIdPrefix: com.diyai
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  defaultConfig: Release
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.diyai.app
    SWIFT_VERSION: 5.9
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    GENERATE_INFOPLIST_FILE: YES
    TARGETED_DEVICE_FAMILY: "1,2"
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: 2.12.0

targets:
  DIYAI:
    type: application
    platform: iOS
    sources:
      - path: DIYAI
    resources:
      - path: DIYAI/Resources
    dependencies:
      - package: Supabase
    info:
      path: DIYAI/Info.plist
      properties:
        CFBundleDisplayName: DIY AI
        NSCameraUsageDescription: We use the camera to capture a photo of the item you want to fix.
        NSPhotoLibraryUsageDescription: Choose a photo from your library to diagnose the issue.
        NSLocationWhenInUseUsageDescription: Use your location to find nearby stores with tools and parts.
        CFBundleURLTypes:
          - CFBundleURLName: com.diyai.app
            CFBundleURLSchemes:
              - diyai
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
    settings:
      base:
        PRODUCT_NAME: "DIY AI"
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG

schemes:
  DIYAI:
    build:
      targets:
        DIYAI: all
    run:
      config: Debug
    test:
      config: Debug
    archive:
      config: Release
    profile:
      config: Release
